version: '2'
services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: trivago-assesment:latest
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    env_file: .env.docker
    working_dir: /app
    command: sh -c ' ./wait-for-it.sh -t 20 trivago_database:3307 -- php artisan key:gen && php artisan migrate && php artisan adverts:poll && php artisan serve --host 0.0.0.0'
    depends_on:
      - db
    links:
      - db
    networks:
    - app-network

  db:
    image: "mysql:5.7"
    container_name: trivago_database
    environment:
      - MYSQL_ROOT_PASSWORD=testpasword
      - MYSQL_DATABASE=trivago
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=thyword123
      - MYSQL_TCP_PORT=3307
    volumes:
      - ./data/:/var/lib/mysql
    ports:
      - "3307:3307"
    networks:
    - app-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      PMA_HOST: trivago_database
      PMA_PORT: 3307
      MYSQL_ROOT_PASSWORD: "testpasword"
    networks:
    - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge